<?php

namespace App\Console\Commands;

use App\Exceptions\Ist\InvalidIstQuestionDatasetException;
use App\Models\Ist\IstQuestion;
use App\Models\Ist\IstQuestionOption;
use App\Models\Ist\IstSubtest;
use App\Models\Ist\IstTest;
use App\Support\Ist\IstAnswerType;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use RuntimeException;

/**
 * One-off content operation: activates a 20-question FA and 20-question WU
 * bank (real-world numbering 117-136 / 137-156) built from original artwork
 * generated by database/data/ist-fa-wu-original/generate.py, deactivating
 * (not deleting) whatever FA/WU scored questions were previously active.
 *
 * Mirrors ist:import-xlsx-question-bank's shape (dry-run by default, active
 * test guard, single transaction), but the source here is a JSON manifest +
 * SVG media directory instead of an xlsx workbook, because FA/WU are
 * image_choice questions with no textual prompt/option content.
 */
final class ImportIstFaWuQuestionBank extends Command
{
    protected $signature = 'ist:import-fa-wu-question-bank
                            {path=database/data/ist-fa-wu-original : Path to the manifest.json + media directory, relative to the project root}
                            {--confirm : Perform the import instead of a dry-run}
                            {--force-active-tests : Proceed even if draft/in-progress IST tests exist (only safe when none are a live participant right now)}';

    protected $description = 'Activate the original 20-question FA/WU image-choice question bank, deactivating the questions it supersedes';

    private const DIFFICULTY_CYCLE = ['easy', 'medium', 'hard'];

    public function handle(): int
    {
        $root = $this->resolvePath((string) $this->argument('path'));
        $manifestPath = $root.'/manifest.json';

        if (! is_file($manifestPath)) {
            $this->error("Manifest not found: {$manifestPath}");

            return self::FAILURE;
        }

        $manifest = json_decode((string) file_get_contents($manifestPath), true);

        if (! is_array($manifest) || ! isset($manifest['fa']['questions'], $manifest['wu']['questions'])) {
            $this->error('Manifest is missing fa/wu question lists.');

            return self::FAILURE;
        }

        $this->assertCount($manifest['fa']['questions'], 20, 'FA');
        $this->assertCount($manifest['wu']['questions'], 20, 'WU');

        $mode = $this->option('confirm') ? 'ACTUAL' : 'DRY-RUN';
        $this->line("IST FA/WU question bank import ({$mode}) from {$root}:");
        $this->line(sprintf('  FA: %d active now -> 20 active after import', $this->activeCount('FA')));
        $this->line(sprintf('  WU: %d active now -> 20 active after import', $this->activeCount('WU')));

        if (! $this->option('confirm')) {
            $this->warn('Dry-run only. Use --confirm to apply changes.');

            return self::SUCCESS;
        }

        if (! $this->option('force-active-tests')) {
            $this->assertNoActiveTests();
        }

        DB::transaction(function () use ($root, $manifest): void {
            if (! $this->option('force-active-tests')) {
                $this->assertNoActiveTests(true);
            }

            $this->importSubtest('FA', $manifest['fa']['questions'], $root, $manifest['fa']['instruction'] ?? null);
            $this->importSubtest('WU', $manifest['wu']['questions'], $root, $manifest['wu']['instruction'] ?? null);
        }, 3);

        $this->info('Import complete.');

        return self::SUCCESS;
    }

    private function importSubtest(string $code, array $questions, string $root, ?string $instruction): void
    {
        /** @var IstSubtest $subtest */
        $subtest = IstSubtest::query()->where('code', $code)->lockForUpdate()->firstOrFail();

        IstQuestion::query()
            ->where('ist_subtest_id', $subtest->id)
            ->where('kind', IstQuestion::KIND_SCORED)
            ->where('is_active', true)
            ->update(['is_active' => false]);

        $nextNumber = 1 + (int) (IstQuestion::withTrashed()
            ->where('ist_subtest_id', $subtest->id)
            ->where('kind', IstQuestion::KIND_SCORED)
            ->max('question_number') ?? 0);

        $version = 1 + (int) (IstQuestion::withTrashed()
            ->where('ist_subtest_id', $subtest->id)
            ->max('version') ?? 0);

        $disk = config('ist.final_media_disk', 'public');

        foreach ($questions as $index => $questionData) {
            $promptDiskPath = $this->publish($root, $questionData['prompt_image'], $code, $disk);

            $question = IstQuestion::create([
                'ist_subtest_id' => $subtest->id,
                'question_number' => $nextNumber + $index,
                'display_order' => $index + 1,
                'kind' => IstQuestion::KIND_SCORED,
                'answer_type' => IstAnswerType::IMAGE_CHOICE,
                'prompt' => $instruction,
                'image_disk' => $disk,
                'image_path' => $promptDiskPath,
                'image_alt' => "Soal {$code} nomor {$questionData['question_number']}",
                'max_score' => 1,
                'difficulty' => self::DIFFICULTY_CYCLE[$index % 3],
                'version' => $version,
                'is_active' => true,
            ]);

            foreach ($questionData['options'] as $optionIndex => $optionData) {
                $optionDiskPath = $this->publish($root, $optionData['image'], $code, $disk);

                IstQuestionOption::create([
                    'ist_question_id' => $question->id,
                    'option_key' => $optionData['key'],
                    'image_disk' => $disk,
                    'image_path' => $optionDiskPath,
                    'image_alt' => "Opsi {$optionData['key']}",
                    'display_order' => $optionIndex + 1,
                    'is_correct' => $optionData['key'] === $questionData['correct_option'],
                    'score_value' => $optionData['key'] === $questionData['correct_option'] ? 1 : 0,
                    'is_active' => true,
                ]);
            }
        }

        $subtest->question_count = IstQuestion::query()
            ->where('ist_subtest_id', $subtest->id)
            ->where('kind', IstQuestion::KIND_SCORED)
            ->where('is_active', true)
            ->count();
        $subtest->save();
    }

    /**
     * Copies a media file from the manifest's source directory onto the
     * configured disk under ist-questions/{fa,wu}/, keyed by content hash so
     * the same shared option image (reused across many questions) is only
     * stored once.
     */
    private function publish(string $root, string $relativeSourcePath, string $code, string $disk): string
    {
        $sourcePath = $root.'/media/'.$relativeSourcePath;

        if (! is_file($sourcePath)) {
            throw new RuntimeException("Missing media file: {$sourcePath}");
        }

        $basename = basename($relativeSourcePath);
        $targetPath = 'ist-questions/'.strtolower($code).'/'.$basename;

        Storage::disk($disk)->put($targetPath, (string) file_get_contents($sourcePath));

        return $targetPath;
    }

    private function assertNoActiveTests(bool $lock = false): void
    {
        $query = IstTest::query()->whereIn('status', [IstTest::STATUS_DRAFT, IstTest::STATUS_IN_PROGRESS]);

        if ($lock) {
            $query->lockForUpdate();
        }

        if ($query->exists()) {
            throw InvalidIstQuestionDatasetException::because('import ditolak karena terdapat test IST draft/in_progress');
        }
    }

    private function resolvePath(string $path): string
    {
        return str_starts_with($path, '/') ? rtrim($path, '/') : base_path($path);
    }

    private function assertCount(array $questions, int $expected, string $code): void
    {
        if (count($questions) !== $expected) {
            throw new RuntimeException(
                "{$code} manifest has ".count($questions)." questions, expected {$expected}."
            );
        }
    }

    private function activeCount(string $code): int
    {
        return IstQuestion::query()
            ->whereHas('subtest', fn ($query) => $query->where('code', $code))
            ->where('kind', IstQuestion::KIND_SCORED)
            ->where('is_active', true)
            ->count();
    }
}
